mix them pixels yooo

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import linear_mixing as lmx

In [2]:
# Magic function to auto-update imported first-party scripts 
%load_ext autoreload
%autoreload 2

# other plotting

In [6]:
data = pd.read_csv("classification_results.csv")

In [ ]:
data.head()

In [ ]:
g = sns.catplot(
    data=data, kind="bar",
    x="Scheme", y="f1-score", hue="Sensor", 
    palette="dark", alpha=.6, height=6,
)
g.despine(left=True)
g.set(ylim = (0.5, 1))
g.set_axis_labels("Classification scheme", " F1 score")
g.legend.set_title("")
g.savefig(r"C:\Users\s4770224\Documents\Work\Writing\Figures\Obj1\part2\class_sensor_scores.svg")

# mixing pixels

In [170]:
material_options = {
    "kelp" : ['ecklonia', 'macrocystis', 'undaria'],
    # "brown_algae" : ['ecklonia', 'macrocystis', 'petalonia', 
    #                  'undaria','acrocarpia', 'cystophora', 'carpophyllum', 'durvillaea', 'hormosira', 'phyllospora', 'sargassum', 'scytosiphon'], 
    "brown_non_kelp" : ['acrocarpia', 'cystophora', 'carpophyllum', 
                         'durvillaea', 'hormosira', 'petalonia','phyllospora', 'sargassum', 'scytosiphon'],
    "red_veg" : ['rhodophyte', 'filamentous_rhodophyte','frondose_rhodophyte',],
    "green_veg" : ['grass', 'ulva'],
    # "non_brown_autos" : ['grass', 'filamentous_rhodophyte',
    #                      'frondose_rhodophyte', 'rhodophyte', 'ulva'],
    # "all_non_kelp_autos" : ['acrocarpia', 'carpophyllum', 'cystophora', 
    #                         'durvillaea', 'filamentous_rhodophyte','frondose_rhodophyte', 'petalonia', 'grass','hormosira','phyllospora', 'rhodophyte',  'sargassum','scytosiphon','ulva'],
    # "all_non_kelp" : ['acrocarpia', 'barnacle_shells', 'carpophyllum',
    #                   'cystophora', 'durvillaea', 'filamentous_rhodophyte','frondose_rhodophyte', 'gravel', 'grass','hormosira','mussels','petalonia','phyllospora', 'rhodophyte', 'rock','sand', 'sargassum', 'scytosiphon', 'shell_litter','rock', 'ulva', 'worm_castings'],
    "mineral" : ['barnacle_shells', 'gravel', 'mussels', 'rock', 'sand', 
                  'shell_litter', 'worm_castings'],
    }
material_options.keys()

dict_keys(['kelp', 'brown_non_kelp', 'red_veg', 'green_veg', 'mineral'])

In [171]:
#Assign fractional cover ranges with simulate within
cover_ranges = {
    "kelp" : (0,0.5),
    #"brown_algae" : (0, 0.5), 
    "brown_non_kelp" : (0,0.3),
    "red_veg" : (0,0.1),
    "green_veg" : (0, 0.2),
    #"non_brown_autos" : (0, 40),
    #"all_non_kelp_autos" : (0, 100),
    #"all_non_kelp" : (0,100),
    "mineral" : (0,0.5),}

In [163]:
data = pd.read_csv("./data/processed/resampled/noisy_Sentinel_2_ABC_resampled.csv", index_col=0)
labels = pd.read_csv("data/labels_prepped.csv", index_col=0)
data = pd.concat([labels["Class"], data], axis = 1)

In [164]:
waters = pd.read_csv("./S2_deep_water_tasmania.csv", index_col=0)
waters = waters.iloc[:, 4:-3]
waters.drop_duplicates(inplace = True)
waters= waters/10000
waters.head()

,nbart_blue,nbart_green,nbart_red,nbart_red_edge_1,nbart_red_edge_2,nbart_red_edge_3,nbart_nir_1,nbart_nir_2
1,0.0323,0.0327,0.0163,0.0168,0.0187,0.0195,0.0203,0.0198
2,0.0327,0.0303,0.0162,0.0177,0.0199,0.0210,0.0182,0.0217
3,0.0309,0.0310,0.0174,0.0177,0.0199,0.0210,0.0193,0.0217
4,0.0316,0.0329,0.0181,0.0192,0.0195,0.0211,0.0192,0.0208
6,0.0344,0.0319,0.0200,0.0192,0.0195,0.0211,0.0218,0.0208

In [176]:
mixer = lmx.LinearMixing(materials = material_options, cover_ranges = cover_ranges, pixels = 100, material_spectra= data, water_spectra = waters)

In [177]:
results, f = mixer.sim_many_pixels()

In [178]:
formatted_results = mixer.format_sim_results(results)
formatted_results.head()

,S2A_SR_AV_B2,S2A_SR_AV_B3,S2A_SR_AV_B4,S2A_SR_AV_B5,S2A_SR_AV_B6,S2A_SR_AV_B7,S2A_SR_AV_B8,S2A_SR_AV_B8A
0,0.060778,0.213653,0.194724,0.332212,0.436834,0.483505,0.523677,0.548613
1,0.024311,0.054891,0.039653,0.162125,0.351302,0.371034,0.338354,0.311929
2,0.023099,0.030692,0.028552,0.118316,0.267460,0.294189,0.324399,0.344584
3,0.024451,0.021137,0.014361,0.036376,0.084745,0.092508,0.094258,0.098992
4,0.047860,0.143775,0.156033,0.278297,0.441638,0.453746,0.445611,0.439456

In [179]:
f

{0: {'brown_non_kelp': 0.22155048450450399, 'mineral': 0.37236677437957955},
 1: {'green_veg': 0.1368555711642084,
  'red_veg': 0.004071670406060039,
  'mineral': 0.09626680484733675,
  'kelp': 0.1864079703216984},
 2: {'kelp': 0.1843541860850509,
  'mineral': 0.2186050000568335,
  'brown_non_kelp': 0.02587352619395561},
 3: {'red_veg': 0.015160898244940369, 'brown_non_kelp': 0.07348392577200322},
 4: {'kelp': 0.08484214337728391,
  'brown_non_kelp': 0.09118298962862005,
  'red_veg': 0.061484261207061075,
  'green_veg': 0.0991452240941358,
  'mineral': 0.16481675640586646},
 5: {'kelp': 0.3311020614079341,
  'red_veg': 0.038446747509805576,
  'brown_non_kelp': 0.1799367446926013},
 6: {'kelp': 0.3268431752818091, 'brown_non_kelp': 0.10871976376576893},
 7: {'kelp': 0.1926435173751916,
  'red_veg': 0.07644654488037887,
  'brown_non_kelp': 0.19852117341232609},
 8: {'kelp': 0.21914572612737993,
  'red_veg': 0.01261590247964819,
  'green_veg': 0.054512297298608695},
 9: {'kelp': 0.11569460112135588, 'red_veg': 0.021553208223522358},
 10: {'mineral': 0.10695246186857932,
  'green_veg': 0.030257091186935973,
  'brown_non_kelp': 0.22299049909687868,
  'kelp': 0.21274066093145133},
 11: {'kelp': 0.1909355647063915},
 12: {'green_veg': 0.06820263237734588,
  'mineral': 0.2739487444857143,
  'red_veg': 0.03553879297087161,
  'brown_non_kelp': 0.09536129056078509},
 13: {'green_veg': 0.14630721569069258,
  'mineral': 0.3234202432222441,
  'kelp': 0.10834633787148676},
 14: {'mineral': 0.2773952424762373},
 15: {'green_veg': 0.07376822688875107},
 16: {'kelp': 0.3936294247325146},
 17: {'green_veg': 0.1028006945581911, 'red_veg': 0.00047217734838229806},
 18: {'mineral': 0.03914256501752428, 'red_veg': 0.05086565298383859},
 19: {'brown_non_kelp': 0.29316786196473366,
  'mineral': 0.27850326325906916,
  'red_veg': 0.037503706052150414,
  'kelp': 0.07331150979583331},
 20: {'brown_non_kelp': 0.2697505036721034,
  'green_veg': 0.0036451550103588186,
  'red_veg': 0.05434275305661499,
  'mineral': 0.2461724599095539},
 21: {'mineral': 0.20891995187770485, 'brown_non_kelp': 0.055202311627017865},
 22: {'mineral': 0.1254722758623253,
  'kelp': 0.16583937380786426,
  'green_veg': 0.03936573724448313,
  'red_veg': 0.050448700150585786},
 23: {'red_veg': 0.009288763030763791, 'green_veg': 0.04056898380592716},
 24: {'green_veg': 0.01786940653234521,
  'mineral': 0.27711580135208436,
  'red_veg': 0.041399924754974046},
 25: {'red_veg': 0.09132984021654389},
 26: {'green_veg': 0.12317273671295359,
  'mineral': 0.4116600113451513,
  'kelp': 0.1924267312767486},
 27: {'green_veg': 0.017720275179218703,
  'red_veg': 0.07560142198675268,
  'brown_non_kelp': 0.021587729045956273,
  'mineral': 0.023554625007252968},
 28: {'brown_non_kelp': 0.042422512498746574,
  'green_veg': 0.18870110436308726,
  'kelp': 0.03718840029636759},
 29: {'brown_non_kelp': 0.09418260176901151, 'green_veg': 0.10601413337852374},
 30: {'green_veg': 0.05546937007087374, 'brown_non_kelp': 0.02382187025905534},
 31: {'kelp': 0.25122224533542326, 'red_veg': 0.06074594217279989},
 32: {'mineral': 0.2666264304616025, 'kelp': 0.11948978323490955},
 33: {'brown_non_kelp': 0.16633527776334026, 'red_veg': 0.045128111717777225},
 34: {'red_veg': 0.09475654726045563, 'kelp': 0.18206584028094294},
 35: {'green_veg': 0.08287308853890499,
  'kelp': 0.26135338339393593,
  'brown_non_kelp': 0.0524616545992354},
 36: {'red_veg': 0.05058848130552626,
  'green_veg': 0.027214692211963834,
  'kelp': 0.4144713848816528},
 37: {'brown_non_kelp': 0.19962927748541417},
 38: {'mineral': 0.4371536934161229},
 39: {'brown_non_kelp': 0.215272600827071},
 40: {'kelp': 0.3026774640371559, 'mineral': 0.02133676340952153},
 41: {'mineral': 0.20669267156908855, 'red_veg': 0.06604003217473096},
 42: {'brown_non_kelp': 0.23471785305061127},
 43: {'brown_non_kelp': 0.12820189100597842, 'kelp': 0.11284815703480512},
 44: {'red_veg': 0.06987480987905242,
  'brown_non_kelp': 0.1926730313071365,
  'kelp': 0.2206821341731423,
  'mineral': 0.08103391595932298},
 45: {'kelp': 0.2781432199875457},
 46: {'green_veg': 0.05905309850180074,
  'kelp': 0.3781600146317666,
  'mineral': 0.27191445037375034},
 47: {'brown_non_kelp': 0.02268064236009778,
  'green_veg': 0.0020231294115594625,
  'red_veg': 0.08912226031361316,
  'mineral': 0.22740617720102294},
 48: {'brown_non_kelp': 0.17047883410728493,
  'kelp': 0.35730558498426196,
  'mineral': 0.1968370477480638},
 49: {'mineral': 0.37053791351016396,
  'red_veg': 0.01747245408874519,
  'brown_non_kelp': 0.013051576570653547,
  'green_veg': 0.05362378185438899},
 50: {'brown_non_kelp': 0.022244020720821232,
  'red_veg': 0.009033521795190118,
  'mineral': 0.24299493655912502,
  'kelp': 0.3433578751892486},
 51: {'kelp': 0.06798463741166783, 'mineral': 0.17609949152143115},
 52: {'green_veg': 0.11251525254676005},
 53: {'kelp': 0.13369770167350736, 'brown_non_kelp': 0.24690466199892006},
 54: {'green_veg': 0.18662855635256098, 'kelp': 0.24248345806336796},
 55: {'brown_non_kelp': 0.005653779027997008},
 56: {'brown_non_kelp': 0.18953579059311673,
  'green_veg': 0.11380523844799517,
  'mineral': 0.05361903547156296,
  'red_veg': 0.04533777169233564},
 57: {'red_veg': 0.07501404449157797,
  'mineral': 0.428855180993497,
  'kelp': 0.2147545899055522},
 58: {'green_veg': 0.0929362539436284,
  'brown_non_kelp': 0.0948104192944332,
  'mineral': 0.042251360785535985},
 59: {},
 60: {'green_veg': 0.03210072045291412,
  'brown_non_kelp': 0.16073875899640291,
  'kelp': 0.01452683368669888},
 61: {'brown_non_kelp': 0.04356414505397719, 'kelp': 0.1269209167111341},
 62: {'mineral': 0.13966252151163144, 'red_veg': 0.06873005108944034},
 63: {'red_veg': 0.02873851154136118,
  'green_veg': 0.008212827792731256,
  'brown_non_kelp': 0.2294470904866874,
  'kelp': 0.3231434582567415},
 64: {'red_veg': 0.02702282707699838,
  'green_veg': 0.03829878671289197,
  'kelp': 0.17275309655851578,
  'brown_non_kelp': 0.08602000323457305},
 65: {'brown_non_kelp': 0.146190055271811, 'kelp': 0.2070958409961557},
 66: {'mineral': 0.15898697071324236, 'brown_non_kelp': 0.167811002947527},
 67: {'kelp': 0.14111201000070822,
  'green_veg': 0.0596784110683507,
  'brown_non_kelp': 0.1084286465272543},
 68: {'mineral': 0.42695511393155927},
 69: {'kelp': 0.3451660167481683,
  'brown_non_kelp': 0.1922221763683801,
  'green_veg': 0.061245748238273875,
  'mineral': 0.1480307263106596},
 70: {'green_veg': 0.1067594043570886},
 71: {'kelp': 0.2679418173537509, 'green_veg': 0.13349479989975513},
 72: {'mineral': 0.46246496786236346,
  'kelp': 0.17273423295487278,
  'brown_non_kelp': 0.04563792070338193},
 73: {'green_veg': 0.01718257678726598},
 74: {'red_veg': 0.04887821405949684,
  'green_veg': 0.042108854380532065,
  'kelp': 0.2987015172875534,
  'brown_non_kelp': 0.16390742975582043,
  'mineral': 0.18287431039905638},
 75: {'green_veg': 0.08205123315005113},
 76: {'brown_non_kelp': 0.18255141991947327,
  'mineral': 0.3700874187558448,
  'kelp': 0.08760106013653958,
  'green_veg': 0.03513616205126853},
 77: {'brown_non_kelp': 0.2528107269362488, 'red_veg': 0.05992761567386951},
 78: {'red_veg': 0.0568784367073033},
 79: {'green_veg': 0.019806138995305946},
 80: {'red_veg': 0.08596206783699357},
 81: {'red_veg': 0.049112382422387336, 'mineral': 0.24109975891532254},
 82: {'red_veg': 0.042924618989875096,
  'mineral': 0.3519834322844251,
  'green_veg': 0.11444993408384231},
 83: {'brown_non_kelp': 0.2034665196148707, 'green_veg': 0.016408883575295626},
 84: {'kelp': 0.2905563862540754,
  'red_veg': 0.02243624509924207,
  'mineral': 0.24974954560918047,
  'brown_non_kelp': 0.03178681841265703,
  'green_veg': 0.0800874244015322},
 85: {'green_veg': 0.052440627006075484,
  'brown_non_kelp': 0.19451742818761433},
 86: {},
 87: {},
 88: {'red_veg': 0.010969032510618749, 'mineral': 0.16905647364667975},
 89: {'brown_non_kelp': 0.06961052832317956},
 90: {'mineral': 0.32352775190179833, 'kelp': 0.03908254880201376},
 91: {'kelp': 0.4622035466187187,
  'mineral': 0.11808926107641111,
  'red_veg': 0.01780435388790679},
 92: {'green_veg': 0.13610143253796378,
  'brown_non_kelp': 0.10713938194142038,
  'mineral': 0.1871993465039024,
  'red_veg': 0.04436438668330297},
 93: {'brown_non_kelp': 0.076134627136544,
  'kelp': 0.3413225425568004,
  'green_veg': 0.09248342328608161},
 94: {'red_veg': 0.09597948910174936, 'mineral': 0.2028672637936514},
 95: {'kelp': 0.004947861714545976,
  'brown_non_kelp': 0.05542762418028572,
  'green_veg': 0.07644317475459363},
 96: {'brown_non_kelp': 0.012020195382455023,
  'kelp': 0.2473935590583,
  'mineral': 0.032132789291150744},
 97: {'red_veg': 0.03477274342547942,
  'mineral': 0.3988914870454985,
  'brown_non_kelp': 0.10144779508779914},
 98: {'brown_non_kelp': 0.18572198204396104,
  'red_veg': 0.027759934838918476,
  'green_veg': 0.06933586922991991},
 99: {'kelp': 0.4456234070238677, 'mineral': 0.19662691075511451}}